version: '3.5'

services:

  postgres:
    image: postgres
    volumes:
      - pgdata:/var/lib/postgresql/
    networks:
      - yatda 

  web:
    build: .
    #env_file: .env_local
    volumes:
      - .:/usr/src/app
    ports:
      - "8000:8000"
    links:
      - postgres
    networks:
      - yatda
    #command: sleep 999999999999
    command: python manage.py runserver 0.0.0.0:8000

volumes:
  pgdata:

networks:
  yatda:
    name: yatda
